### ISSUE TITLE
Crash on feed search

### ISSUE THREAD

**Issue by hasezoey** [tramhao/termusic#209]
When trying to search in podcasts (prompt `Add or search podcast feed`), when searching for *anything* that is not starting with a protocol will crash with:

```txt
thread 'main' panicked at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/shutdown.rs:51:21:
Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: tokio::runtime::blocking::shutdown::Receiver::wait
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/shutdown.rs:51:21
   3: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/pool.rs:261:12
   4: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/blocking/pool.rs:278:9
   5: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ptr/mod.rs:507:1
   6: core::ptr::drop_in_place<tokio::runtime::runtime::Runtime>
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ptr/mod.rs:507:1
   7: reqwest::blocking::wait::enter
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.23/src/blocking/wait.rs:76:21
   8: reqwest::blocking::wait::timeout
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.23/src/blocking/wait.rs:13:5
   9: reqwest::blocking::client::ClientHandle::new
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.23/src/blocking/client.rs:1075:15
  10: reqwest::blocking::client::ClientBuilder::build
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.23/src/blocking/client.rs:103:9
  11: termusic::ui::components::podcast::<impl termusic::ui::model::Model>::podcast_search_itunes
             at ./tui/src/ui/components/podcast.rs:377:21
  12: termusic::ui::model::update::<impl termusic::ui::model::Model>::update_podcast
             at ./tui/src/ui/model/update.rs:231:21
  13: termusic::ui::model::update::<impl tuirealm::core::Update<termusiclib::types::Msg> for termusic::ui::model::Model>::update
             at ./tui/src/ui/model/update.rs:170:36
  14: termusic::ui::UI::run_inner::{{closure}}
             at ./tui/src/ui/mod.rs:121:35
  15: termusic::ui::UI::run::{{closure}}
             at ./tui/src/ui/mod.rs:80:36
  16: termusic::actual_main::{{closure}}
             at ./tui/src/main.rs:137:14
  17: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/park.rs:282:63
  18: tokio::runtime::coop::with_budget
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:107:5
  19: tokio::runtime::coop::budget
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/coop.rs:73:5
  20: tokio::runtime::park::CachedParkThread::block_on
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/park.rs:282:31
  21: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/blocking.rs:66:9
  22: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/mod.rs:87:13
  23: tokio::runtime::context::runtime::enter_runtime
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/context/runtime.rs:65:16
  24: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/scheduler/multi_thread/mod.rs:86:9
  25: tokio::runtime::runtime::Runtime::block_on
             at /home/hasezoey/.local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.35.1/src/runtime/runtime.rs:350:45
  26: termusic::actual_main
             at ./tui/src/main.rs:139:5
  27: termusic::main
             at ./tui/src/main.rs:51:23
  28: core::ops::function::FnOnce::call_once
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/ops/function.rs:250:5
```

my quick guess is that this is a similar problem as what we had recently with the `YoutubeOptions` side #158

**Comment by tramhao** [comment]
I searched today and it's all right. Have you fixed it?

**Comment by hasezoey** [comment]
I have not touched that part yet and can still reproduce it in latest master (as of ac006a8c34763b7181371e948109964c4fcc5340).

The problem only occurs in *debug* builds, because reqwest does a debug-assertion to check if it is already in a tokio runtime (the same error we worked-around in / that caused 510decaf3b1b8212c0c2d9785f6e058413ebf16e)
