### ISSUE TITLE
Panic occurred, unwrap on error NameTaken

### ISSUE THREAD

**Issue by sigurd4** [tramhao/termusic#398]
## Environment & Versions

- System: Arch Linux x86_64 / 6.12.3-arch1-1
- Termusic version: termusic-git 0.9.1.r180.gd82806c-1 (AUR)
- Rust version: 1.85.0-nightly (4c39aaff6 2024-11-25)

## Logs:

<details>
<summary>Logs</summary>

```
[2024-12-09T22:59:43.712+01:00 ERROR termusic_server::logger]: Panic occured:
panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:100:22:
called `Result::unwrap()` on an `Err` value: NameTaken
disabled backtrace
thread '<unnamed>' panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:100:22:
called `Result::unwrap()` on an `Err` value: NameTaken
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2024-12-09T22:59:43.811+01:00 ERROR termusic_server::logger]: Panic occured:
panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:139:29:
called `Result::unwrap()` on an `Err` value: SendError { .. }
disabled backtrace
thread 'main player loop' panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:139:29:
called `Result::unwrap()` on an `Err` value: SendError { .. }
[2024-12-09T22:59:43.811+01:00 ERROR termusic_server::logger]: Panic occured:
panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:112:53:
called `Result::unwrap()` on an `Err` value: SendError { .. }
disabled backtrace
thread 'main player loop' panicked at /home/sigurd/.cargo/registry/src/index.crates.io-6f17d22bba15001f/souvlaki-0.7.3/src/platform/mpris/zbus.rs:112:53:
called `Result::unwrap()` on an `Err` value: SendError { .. }
stack backtrace:
   0:     0x638ea67af4f9 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h5b6bd5631a6d1f6b
   1:     0x638ea6455b83 - core::fmt::write::h7550c97b06c86515
   2:     0x638ea67776c2 - std::io::Write::write_fmt::h7b09c64fe0be9c84
   3:     0x638ea67b0eb2 - std::sys::backtrace::BacktraceLock::print::h2395ccd2c84ba3aa
   4:     0x638ea67b0d1b - std::panicking::default_hook::{{closure}}::he19d4c7230e07961
   5:     0x638ea67b0acc - std::panicking::default_hook::hf614597d3c67bbdb
   6:     0x638ea68b6ffa - termusic_server::logger::setup::{{closure}}::h634a14e966301138
   7:     0x638ea67b1179 - std::panicking::rust_panic_with_hook::h8942133a8b252070
   8:     0x638ea67b0f88 - std::panicking::begin_panic_handler::{{closure}}::hb5f5963570096b29
   9:     0x638ea67b0ee9 - std::sys::backtrace::__rust_end_short_backtrace::h6208cedc1922feda
  10:     0x638ea67b0edc - rust_begin_unwind
  11:     0x638ea636a6bf - core::panicking::panic_fmt::h0c3082644d1bf418
  12:     0x638ea636aa95 - core::result::unwrap_failed::hd20b4aa073bda1e2
  13:     0x638ea674392b - souvlaki::platform::platform::zbus::MediaControls::detach::h43e67df9f2c5da9b
  14:     0x638ea68e4bc9 - core::ptr::drop_in_place<core::option::Option<termusicplayback::mpris::Mpris>>::h53ef9f03b3a1539a
  15:     0x638ea68e4157 - core::ptr::drop_in_place<termusicplayback::GeneralPlayer>::ha1ffb2feef179154
  16:     0x638ea68e3c64 - termusic_server::player_loop::he45a143d1f69877c
  17:     0x638ea68b3ade - std::sys::backtrace::__rust_begin_short_backtrace::h469ea57f34df9fda
  18:     0x638ea68ddd28 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h4e83e14fd262d8fd
  19:     0x638ea67b225b - std::sys::pal::unix::thread::Thread::new::thread_start::hcc78f3943333fa94
  20:     0x77e7ab14a39d - <unknown>
  21:     0x77e7ab1cf49c - <unknown>
  22:                0x0 - <unknown>
[2024-12-09T22:59:43.818+01:00 ERROR termusic_server::logger]: Panic occured:
panicked at core/src/panicking.rs:229:5:
panic in a destructor during cleanup
```

</details>

## Description of the Problem

`termusic-server` cannot start and produces the panic above every time. I think it was because the port was wrong (name taken?), but the error doesn't tell me much.

## Steps to reproduce

- Change the port to `50102`.
- Run `termusic-server`

Changing it back to `50101` makes everything run fine again.

**Comment by hasezoey** [comment]
From the Error, it seems like termusic cannot connect to MPRIS, as the name we use is already taken in dbus. Is there maybe a residual termusic instance in the background still active?

There is sadly nothing we can really do about this panicing currently aside from opening a issue in souvlaki to handle it non-panicing.
